all:
	java -cp "saxon9he.jar" net.sf.saxon.Query -s:dblp-exceprt.xml -q:request.xquery -o:output.xml
test:
	java -cp "saxon9he.jar" net.sf.saxon.Query -s:litle_dblp-exceprt.xml -q:request.xquery -o:test_output.xml